[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quoridor"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy"
]

[project.optional-dependencies]
ml = ["tensorflow"]
x = ["matplotlib"]
all = ["tensorflow", "matplotlib"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN101", "ANN102", "ERA001", "T201", "COM812", "ISC001"]
